### ISSUE TITLE
errore in inserimento ticket

### ISSUE THREAD

**Issue by mariaranci** [ARPASMR/web#20]
ho aperto un ticket su due sensori di una stazione. Le annotazioni vengono correttamente inserite ma senza ticket associato, il ticket non viente creato.
Messaggio di errore:

Notice: Undefined index: IdSensore in /srv/www/htdocs/anagrafica/ticket.php on line 150
Sensore #19022 - Errore nel salvataggio dei dati.
Sensore #19023 - Salvataggio avvenuto correttamente.

**Comment by lucapaganotti** [comment]
Presente un errore nella valutazione del numero di salvataggi da eseguire e sui risultati delle singole operazioni di salvataggio. E' stata modificata la logica di controllo dei risultati delle query nel caso di inserimento/modifica di annotazioni relative al singolo sensore, a sottoinsiemi di sensori afferenti alla medesima stazione in esame, a tutti i sensori afferenti alla stazione in esame (Annotazione Stazione). Ora viene data notifica all'utente in tutti i casi in maniera dettagliata.
