### ISSUE TITLE
update tabella sensori non va a buon fine

### ISSUE THREAD

**Issue by mariaranci** [ARPASMR/web#21]
la pagina "Modifica sensore", anche senza apportare modifiche, al momento del salvataggio riporta l'errore in allegato
![cattura](https://user-images.githubusercontent.com/31917865/45489247-144cf300-b764-11e8-8be7-9cc9f59ed672.PNG)

**Comment by lucapaganotti** [comment]
Errore durante la procedura di update di oggetti spaziali nel database. Corretta la procedura update nel file DBInterface.php
