### ISSUE TITLE
errore in inserimento nuova stazione

### ISSUE THREAD

**Issue by mariaranci** [ARPASMR/web#22]
in inserimento nuova stazione viene restituito l'errore in allegato
![cattura](https://user-images.githubusercontent.com/31917865/45738305-55278a80-bbf0-11e8-95eb-eb5b00540e42.PNG)

**Comment by lucapaganotti** [comment]
Errore durante la procedura di update di oggetti spaziali nel database. Corretta la procedura insert nel file DBInterface.php. Purtroppo esiste anche la procedura insert che segue la stessa logica della procedura update (vedi issue #21), perdonate la leggerezza.
