### ISSUE TITLE
numero sensori/stazioni selezionate

### ISSUE THREAD

**Issue by mariaranci** [ARPASMR/web#26]
sulla striscia con sfondo giallo in cima alla pagina, viene riportato il numero di sensori o stazioni risultato della select effettuata, ma il conteggio considera solo il filtro eseguito tramite il menù di sinistra e ignora i filtri tramite ricerca stringhe all'interno della pagina.
Sostituire con il numero di sensori o stazioni selezionati indipendentemente da come è avvenuta la selezione. 
La modifica è analoga a quella effettuata tempo fa sul bottone "genera CSV"

**Comment by lucapaganotti** [comment]
Modificate le liste di stazioni e sensori nella parte relativa ai filtri liberi in modo da effettuare un conteggio corretto ogni volta che uno o più valori contenuti nella caselle di testo dei filtri di colonna cambiano.
