### ISSUE TITLE
informazioni da MINIO

### ISSUE THREAD

**Issue by mariaranci** [ARPASMR/web#27]
aggiungere un bottone "Scheda" nella pagina della stazione che acceda al bucket di Minio http://10.10.99.135:9000/minio/rete-monitoraggio/prodotti/schedestazioni/
e visualizzi 'IDsensore'_main.html, LOGO_ARPA.jpg e R2HTML.css

eliminare la voce "- Schede Stazioni" dall'elenco dei link nel menù a sinistra

**Comment by mauromussin** [comment]
Schede_stazioni deve essere linkato a https://arpalombardia.sharepoint.com/:f:/r/sites/grpsc-sopralluoghiretiinm/Rete%20di%20Monitoraggio/Schede_stazioni?csf=1&e=aL2w1S

**Comment by lucapaganotti** [comment]
Schede_Stazioni ora punta all'URL https://arpalombardia.sharepoint.com/:f:/r/sites/grpsc-sopralluoghiretiinm/Rete%20di%20Monitoraggio/Schede_stazioni?csf=1&e=aL2w1S.
