### ISSUE TITLE
errore in "modifica stazione"

### ISSUE THREAD

**Issue by mariaranci** [ARPASMR/web#28]
il campo NoteManutenzione viene correttamente visualizzato alla voce Manutenzione della pagina Dettaglio Stazioni (concatenando le due stringhe)

una volta compilato, però, se si torna alla pagina "modifica stazione" si perde memoria della stringa e il campo torna vuoto

**Comment by lucapaganotti** [comment]
Ora il campo NoteManutenzione viene gestito correttamente, il problema risiedeva nel form di modifica dell'oggetto Stazione, uno degli attributi del form di modifica era scritto in maniera erronea `alue` al posto di `value`.
