### ISSUE TITLE
tabelle di legenda

### ISSUE THREAD

**Issue by mariaranci** [ARPASMR/web#29]
nel riquadro a sinistra aggiungere le 2 voci "Destinazioni" e "Classificazioni"
e differenziare visivamente le prime due tabelle da quelle di legenda. Per esempio con una riga vuota o indentando come segue:

Consultazione Anagrafica
------------------------------------
- Stazioni
- Sensori

	- Tipologie
	- Destinazioni
	- Classificazioni 
--------------------------------

le due pagine nuove riportano i seguenti campi rispettivamente:

A_Destinazioni.IDdestinazione concatenato con A_Destinazioni.Destinazione as DBmeteo
A_Destinazioni.IDdestinazioneREM concatenato con A_Destinazioni.DestinazioneREM e con Note as REM

A_Classificazione.IDclasse as Classe
A_Classificazione.Descrizione as Descrizione

**Comment by lucapaganotti** [comment]
Rinominati file Destinazione.php in SensoriDestinazione.php, creati i file Classificazione.php, Destinazione.php, classificazioni.php, destinazioni.php. Implementato quanto richiesto.
