### ISSUE TITLE
permettere identificativi di Tipologia > 255

### ISSUE THREAD

**Issue by mariaranci** [ARPASMR/web#33]
il campo METEO.A_Tipologia.IdTipologia è cambiato da tinyint a small int perchè esiste la tipologia numero 310. 
Permettere la visualizzazione di valori >255 nell'interfaccia

**Comment by lucapaganotti** [comment]
Dovrebbe essere già possibile farlo, il database supporta per il campo IdTipologia, valori numerici fino a 5 cifre, per la parte di interfaccia controllata il problema non sussiste. Qualora si verificassero errori o incongruenze, meglio che se ne prenda nota.
