### ISSUE TITLE
legenda destinazioni

### ISSUE THREAD

**Issue by mariaranci** [ARPASMR/web#36]
c'è un errore nella pagina
![Cattura](https://user-images.githubusercontent.com/31917865/69060923-867c3000-0a18-11ea-8023-a5a6a6ad0c76.PNG)

**Comment by mariaranci** [comment]
https://sinergicoweb.docker.arpa.local/anagrafica/destinazioni.php

**Comment by lucapaganotti** [comment]
Ripristinata la legenda delle destinazioni.
SOLVED
