### ISSUE TITLE
pagina "Modifica strumento"

### ISSUE THREAD

**Issue by mariaranci** [ARPASMR/web#38]
nella pagina per creare nuovi strumenti compare le scritta:
Notice: Undefined offset: 0 in /srv/www/htdocs/anagrafica/resources/php/dbMeteo/SensoreSpecifiche.php on line 78

poi l'utente Ranci può inserire dati e creare un nuovo strumento. L'utente GCamisani vede i campi Marca e Modello ma non sono valorizzabili (gli altri sì)

**Comment by lucapaganotti** [comment]
Eliminate le notifiche a video relative a warning e notice in questo form.
SOLVED
