### ISSUE TITLE
bachi validatore docker

### ISSUE THREAD

**Issue by msalvati** [ARPASMR/web#43]
-  il validatore su sinergicoweb.docker non plotta i grafici se nel periodo scelto è presente una chiusura di annotazione con metadato (che dovrebbe venire plottata come barra verticale nel grafico)

- il validatore su sinergicoweb.docker dà errore sul link "destinazioni"

(più info su canale teams dockerizzazione sinergico)

**Comment by lucapaganotti** [comment]
Penso che la questione sia stata risolta a seguito della nostra ultima riunione in merito e dell'installazione della nuova release del validatore all'interno di ghost 3.0. Eventualmente riapriamo issue.
