### ISSUE TITLE
controllo in inserimento sensori di destinazioni

### ISSUE THREAD

**Issue by mariaranci** [ARPASMR/web#48]
nell'esecuzione della maschera "Aggiungi Destinazione" inserire un controllo per cui vada a buon fine solo se il sensore non è già presente nelle destinazione scelta (ossia non esista un record relativo al sensore e alla destinazione con DataFine non valorizzato)

**Comment by lucapaganotti** [comment]
E' stata implementata la funzionalità richiesta. Nel caso sia già presente per il sensore in oggetto la destinazione che si vuole inserire con data di fine periodo non valorizzata viene prodotto un messaggio di errore con delle indicazioni in merito.
SOLVED
