### ISSUE TITLE
allargare o rimuovere vincolo numero di caratteri in campo A_Sensori.AggregazioneTemporale

### ISSUE THREAD

**Issue by mariaranci** [ARPASMR/web#49]
in creazione o modifica di un nuovo sensore allargare a 4 o rimuovere il vincolo che permette di valorizzare AggregazioneTemporale con numeri massimo a 3 caratteri (insufficienti per i dati giornalieri)

**Comment by lucapaganotti** [comment]
`ALTER TABLE A_Sensori MODIFY AggregazioneTemporale SMALLINT(5) unsigned NULL;`

Modificato tipo di dati per colonna Aggregazione Temporale di A_Sensori per ospitare interi senza segno da 0 a 99999.
