### ISSUE TITLE
allargare il vincolo sulla lunghezza del testo in A_Monitoraggio.Note

### ISSUE THREAD

**Issue by mariaranci** [ARPASMR/web#53]
modificare il vincolo in oggetto da 250 caratteri a 500

**Comment by mariaranci** [comment]
Nelle pagine "Crea nuova Annotazione" e "Modifica Annotazione", nella compilazione del campo "Annotazione"

**Comment by lucapaganotti** [comment]
Ora la validazione del campo Note relativo alle annotazioni considera una lunghezza massima di 500 caratteri.
SOLVED
