### ISSUE TITLE
nuove etichette di Metadato

### ISSUE THREAD

**Issue by mariaranci** [ARPASMR/web#55]
nelle annotazioni abbiamo modificato la scelta delle stringhe da inserire nel campo A_Monitoraggio.Metadato. Dobbiamo decidere come gestire la cosa tramite interfaccia

**Comment by lucapaganotti** [comment]
Mi sembra che questa issue possa considerarsi chiusa, la scelta delle etichette di metadato si è conclusa e il codice sorgente è stato modificato di conseguenza.
